### ISSUE TITLE
Implement Coop Default Governance, Staking and Investment logic

### ISSUE THREAD

**Issue by molekilla** [Electronic-Signatures-Industries/PanamaDAO#5]
- [ ] El Estatuto deberá establecer el capital social mínimo.
- [ ] El ejercicio socioeconómico será de doce meses, comprendido dentro de un
período cuya fecha de inicio y terminación establecerá el Estatuto.
- [ ] Los excedentes que arroje el balance anual, después de descontados los gastos
generales y las provisiones, serán distribuidos por acuerdo de la asamblea, en la
siguiente forma y orden de prelación:
1. Por lo menos, el diez por ciento (10%) para la reserva patrimonial; nueve y
medio por ciento (9.5%) para el fondo de previsión social; diez pro ciento (10%)
para el fondo de educación, medio por ciento (0.5%) para el fondo de integración y
cinco por ciento (5%) para constituir, en el IPACOOP, el fondo anual especial para
el fomento y desarrollo cooperativo;
2. La suma que señala el estatuto o la asamblea para fines específicos;
3. El interés que devenguen las aportaciones, conforme lo establezca el estatuto;
4. La devolución a los asociados, en proporción a las operaciones que hubieran
efectuado con la cooperativa o a su participación en el trabajo común.
- [ ] La reserva patrimonial tiene por objeto asegurar a las cooperativas la normal
realización de sus actividades, habilitarlas para cubrir las pérdidas que se
produzcan en un ejercicio económico y ponerlas en situación de satisfacer
exigencias imprevistas o necesidades financieras que puedan presentarse, y se
regirá por las disposiciones siguientes:
1. Será facultad de la asamblea establecer que la reserva patrimonial sea limitada,
y tal determinación deberá establecerse en el estatuto de la cooperativa;
2. Cuando la reserva patrimonial sea limitada, no podrá exceder el veinte por
ciento (20%) de las aportaciones pagadas;
3. Para constituir e incrementar la reserva patrimonial, se destinará, por lo menos
el diez (10%) de los excedentes netos obtenidos. Ingresarán, además los fondos
irrepartibles y todas las sumas que no tuvieren destino específico, sin perjuicio de
que pueda incrementarse por otros medios;
4. Si la reserva patrimonial disminuyese por cualquier causa, el IPACOOP deberá
ser notificado inmediatamente. Los excedentes futuros serán utilizados para
restituir el nivel que tenía anteriormente.
- [ ] El fondo de previsión social no podrá exceder del veinte por ciento (20%) de la
suma de las aportaciones pagadas por los asociados, más los excedentes no
distribuidos, y se sujetará a las disposiciones siguientes:
1. Cuando este fondo exceda al tope máximo establecido, el excedente será
transferido a la reserva patrimonial o al fondo de educación;2. Cuando lo disponga la asamblea, el fondo de previsión social se podrá utilizar
para seguros colectivos sobre riesgos inherentes a las actividades que realicen,
indemnizaciones a familiares en caso de muerte de asociados, asistencia médica
y donaciones sociales.
Las cooperativas establecerán reglamentos para tales servicios.
- [ ] ARTÍCULO 77:
Las cooperativas podrán constituir y manejar, de acuerdo con las leyes vigentes,
fondos de retiros, cesantías y pensiones y jubilaciones especiales, directamente o
por medio de sus federaciones y entidades auxiliares. Estos fondos serán
inembargables.
- [ ] La cooperativa podrá crear un fondo rotatorio con los excedentes e intereses de
los asociados, que serán devueltos en caso de que éstos se retiren. La junta de
directores, deberá reglamentar el aporte mínimo y máximo que debe ahorrar cada
asociado, el período de rotación del fondo y el porcentaje de los intereses y
excedentes que se capitalizarán. Este fondo se sujetará a las reglas siguientes:
1. El fondo creado con los intereses y excedentes podrá ser incrementado con
otros aportes, tales como efectivo, descuentos autorizados por el asociado o
partidas de los fondos de la cooperativa. En todo caso, el fondo rotatorio debe
tener por objetivo el fomento de actividades productivas de la cooperativo;
2. La asamblea podrá acordar el reconocimiento de un interés por el uso del
capital aportado a este fondo.
- [ ] Las cooperativas podrán emitir certificados de inversión y otros títulos-valores,
redimibles y de plazo fijo, emitidos para reforzar el activo de las cooperativas. Su
producto se destinará al cumplimiento de objetivos específicos.
La emisión de estos certificados de inversión y otros títulos-valores, debe ser
aprobada por asamblea y autorizada previamente por el IPACOOP.
- [ ] Las reservas patrimoniales, el fondo de educación, el fondo de previsión social, así
como las donaciones y legados, son irrepartibles.
- [ ] Los certificados de inversión y otros títulos-valores serán nominativos y
transferibles, y su valor nominal, así como el interés que devenguen, se abonará
con preferencia a cualquier otro pago que tenga que realizar la cooperativa.
- [ ] Los intereses y demás beneficios que provengan del capital invertido por los
asociados, sus depósitos y los títulos-valores invertidos por los asociados y
terceros, estarán exentos de toda clase de impuestos, derechos, contribuciones o
gravámenes de carácter general.
- [ ] Las cooperativas podrán asumir todas las formas de pasivos y emitir obligaciones
que suscribirán los asociados a los terceros, conforme a las condiciones que
establezca la respectiva reglamentación.
- [ ] Las cooperativas podrán recibir, de personas públicas o privadas, asignaciones,
legados y otros aportes destinados a incrementar su patrimonio o a ser
consumidos de conformidad con la voluntad el aportante. En ambos casos,
estarán orientados al cumplimiento del respectivo objeto social.
